# Generated by Django 4.2 on 2023-05-02 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_product_expirationdate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
